# Baby Steps - Algebra
Notes based on http://deeplearning.net/software/theano/tutorial/adding.html.

In [1]:
import numpy as np
import theano.tensor as T
from theano import function

### Adding two scalars
First, something simple: adding two numbers. To do so, we define two variables that we want to add. In theano, all variables are typed. __dscalar__ is the type of a double scalar. Calling __dscalar__ with a string argument creates a named variable for a float scalar (the name is optional).

In [2]:
x = T.dscalar('x')
y = T.dscalar('y')

Note: __dscalar__ is not a class. $x$ and $y$ are instances of __TensorVariable__. They are assigned the type __dscalar__, however.

In [3]:
x.type is T.dscalar

True

Combining $x$ and $y$ produces a variable $z$ which represents the addition of $x$ and $y$.

In [4]:
z = x + y

Finally, we create a function that takes $x$ and $y$ as inputs and returns $z$:

In [5]:
f = function([x, y], z)

The first argument is a list of variables provided as inputs, while the second argument can be a single variable _or_ a list. The function can be called like this:

In [6]:
f(2, 3)

array(5.0)

Note: There's also __z.eval()__, which can be passed a dictionary mapping $x$ and $y$ to values. It doesn't need to import __function()__, but is otherwise less flexible.
### Adding two matrices
Now, instead of instantiating $x$ and $y$ as scalars, we create them as matrix types and create another function $f$ to add them.

In [7]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)

We can now use it to sum up matrices, i.e. 2d arrays (1d arrays are vectors). Note: They need to have the same dimensions, naturally.

In [8]:
f([[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[  6.,   8.],
       [ 10.,  12.]])

Numpy arrays can also be used directly as inputs.

In [9]:
f(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]))

array([[  6.,   8.],
       [ 10.,  12.]])

Available types are __scalar__, __vector__, __matrix__, __row__, __col__, __tensor3__, and __tensor4__. They are prefixed in each case with __b__ (byte), __w__ (16-bit int), __i__ (32-bit int), __l__ (64-bit int), __f__ (float), __d__ (double), and __c__ (complex).

### Exercise
Computation of $a^2 + b^2 + 2 a b$:

In [10]:
a = T.vector()
b = T.vector()
out = a ** 2 + b ** + 2 * a * b
f = function([a, b], out)
f([1, 2], [3, 4])

array([  28.,  132.])