# NumPy refresher
Notes based on http://deeplearning.net/software/theano/tutorial/numpy.html

In [1]:
import numpy as np

Every row conforms to one input instance. The following produces a 3x2 matrix.

In [2]:
this_array = np.asarray([[1, 2], [3, 4], [5, 6]])
print this_array

[[1 2]
 [3 4]
 [5 6]]


Access is done as usual:

In [3]:
this_array[2, 0]

5

_Broadcasting_ refers to expanding a scalar (or smaller array) to the same size as the bigger one during arithmetic operations.

In [4]:
my_scalar = 2.0
this_array * my_scalar

array([[  2.,   4.],
       [  6.,   8.],
       [ 10.,  12.]])

That was straight-forward, but kind of dull. Now on to more fun exercises. But first, some more notes.

####Quicker initilization of arrays

In [5]:
x = np.arange(6) # 1-d array in the specified range
x = x.reshape(2, 3) # transform in other dimensions
x

array([[0, 1, 2],
       [3, 4, 5]])

Arrays can be prepoluted with zeros or ones like this:

In [6]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones((3, 2), dtype=float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

You can also initialize an array randomly like this, either with an int or a double.

In [8]:
np.random.randint(0, 2, (2, 5))

array([[1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0]])

In [9]:
np.random.rand(2, 3)

array([[ 0.8282987 ,  0.13097362,  0.60294391],
       [ 0.97016251,  0.83482886,  0.81753832]])

Setting all entries of an existing array to a number looks like this:

In [10]:
x[...] = 0
x

array([[0, 0, 0],
       [0, 0, 0]])

#### Checking conditions

__numpy.argwhere__: returns indexes of non-zero elements or elements that fulfil a certain condition.

In [11]:
np.argwhere(x) # returns non-zero indeces

array([], shape=(0, 2), dtype=int64)

In [12]:
np.argwhere(x>1) # returns indeces of elements > 1

array([], shape=(0, 2), dtype=int64)

#### Flattening arrays

In [13]:
x.ravel()

array([0, 0, 0, 0, 0, 0])

#### Structured arrays
An array can have multiple data types. An array with more than one data type, i.e. a structured array, can store structs or records. We can initialize an array of length 2 containing a 32-bit integer (_i4_), a 32-bit float (_f4_), and a string of length 10 or less (_a10_) like this:

In [14]:
x = np.zeros((2,),dtype=('i4, f4 , a10')) 
x[:] = [(1 , 2., 'Hello'), (2, 3., "World")]
x

array([(1, 2.0, 'Hello'), (2, 3.0, 'World')], 
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

We can retrieve the values the same way as usual.

In [15]:
x[1]

(2, 3.0, 'World')

We can also access the fields with the string that names the field, i.e. the default names _f0_, _f1_, and _f2_.

In [16]:
y = x['f1']
y

array([ 2.,  3.], dtype=float32)

Again, changing the value of a field changes the value of the whole array.

In [17]:
x[1] = (-1, -1., 'Universe')
x

array([(1, 2.0, 'Hello'), (-1, -1.0, 'Universe')], 
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

More information on structured arrays can be found [here](http://docs.scipy.org/doc/numpy/user/basics.rec.html).